/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    nativeCreateInnerClassInstance
 * Signature: (Ljava/lang/String;I)LTestJNI/InnerClass;
 */
JNIEXPORT jobject JNICALL nativeCreateInnerClassInstance
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     TestJNI
 * Method:    nativePrintInnerClassInstance
 * Signature: (LTestJNI/InnerClass;)V
 */
JNIEXPORT void JNICALL nativePrintInnerClassInstance
  (JNIEnv *, jclass, jobject);

/*
 * Class:     TestJNI
 * Method:    nativePrintInnerClassInstanceByCallingJavaMethod
 * Signature: (LTestJNI/InnerClass;)V
 */
JNIEXPORT void JNICALL nativePrintInnerClassInstanceByCallingJavaMethod
  (JNIEnv *, jclass, jobject);

/*
 * Class:     TestJNI
 * Method:    nativeCallInnerClassStaticPrintMethodNativeThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL nativeCallInnerClassStaticPrintMethodNativeThread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
